### ISSUE TITLE
Can't index video with two dashes in link

### ISSUE THREAD

**Issue by rklasen** [yoeven/ai-video-search-engine#1]
Hi, thanks for this great tool.

I've just tried to index a video "https://www.youtube.com/watch?v=UoB-J-eDvrg", which failed. Another video I tried worked without issues.

**Comment by yoeven** [comment]
Hey there! I've gone ahead and indexed the video, it seems related to a bug on vercel where the default fetch fails sometimes when the body data is huge and in this case the video was long so it failed to be added into the database due to this bug. I've tried making a small adjustment that hopfully fixes it.

I've tried a few long form videos from the same channel and it seems to work now, let me know if you face this issue again. Thanks!
